// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0SHn8LAkdsyRZEw-EvOA0Wze_4F3Z04g',
    appId: '1:896640996837:web:afb3e58630e0a67f1b4b0c',
    messagingSenderId: '896640996837',
    projectId: 'garden-16760',
    authDomain: 'garden-16760.firebaseapp.com',
    storageBucket: 'garden-16760.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF7VB7zOEap_pRW67hWOzPhfNytAwTLOQ',
    appId: '1:896640996837:android:5de7098f0264f0871b4b0c',
    messagingSenderId: '896640996837',
    projectId: 'garden-16760',
    storageBucket: 'garden-16760.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0SHn8LAkdsyRZEw-EvOA0Wze_4F3Z04g',
    appId: '1:896640996837:web:fffe37cd1c1da1301b4b0c',
    messagingSenderId: '896640996837',
    projectId: 'garden-16760',
    authDomain: 'garden-16760.firebaseapp.com',
    storageBucket: 'garden-16760.appspot.com',
  );
}
